import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'

import { Button } from '@/components/button'
import { Container } from '@/components/container'
import { Footer } from '@/components/footer'
import { Navbar } from '@/components/navbar'

export const metadata: Metadata = {
  title: 'Carroattrezzi a Brescia 24H | Soccorso stradale',
  description: 'Carroattrezzi a Brescia attivo 24 ore su 24 per traino auto, recupero veicoli, moto e assistenza stradale in città e provincia.',
  alternates: { canonical: '/' },
  openGraph: {
    title: 'Carroattrezzi a Brescia 24H | Soccorso stradale',
    description: 'Soccorso stradale, traino e recupero veicoli a Brescia e provincia.',
    images: ['/images/recovery-operation.jpg'],
  },
}

const phone = '030 204 1924'
const tel = 'tel:+390302041924'
const address = 'Via Antonio Allegri, 8725124 Brescia BS'

const services = [
  ['Soccorso stradale 24 ore', 'Assistenza per auto ferme, guasti improvvisi e situazioni in cui proseguire non è sicuro.'],
  ['Traino auto', 'Trasporto verso officina, carrozzeria, deposito o altra destinazione concordata.'],
  ['Recupero auto incidentata', 'Messa in sicurezza e movimentazione del veicolo dopo un sinistro, con attenzione ai danni presenti.'],
  ['Carroattrezzi moto e scooter', 'Recupero di due ruote ferme, cadute o danneggiate con fissaggi adeguati.'],
  ['Assistenza batteria scarica', 'Valutazione del mancato avviamento e organizzazione del recupero quando l’auto non può ripartire.'],
  ['Recupero auto in panne', 'Intervento per motore fermo, spie accese, perdita di potenza o guasti che impediscono di proseguire.'],
  ['Soccorso furgoni', 'Supporto per furgoni leggeri e veicoli commerciali bloccati durante il lavoro o una consegna.'],
  ['Soccorso in autostrada', 'Indicazioni e recupero per veicoli fermi lungo i collegamenti autostradali e le tangenziali.'],
  ['Trasporto veicoli', 'Trasferimento programmato di auto, moto e mezzi non circolanti verso una destinazione precisa.'],
]

const zones = ['Brescia', 'Roncadelle', 'San Zeno Naviglio', 'Borgosatollo', 'Castel Mella', 'Concesio', 'Rezzato', 'Gussago', 'Cellatica', 'Nave', 'Botticino', 'Flero']

const faqs = [
  ['Quanto tempo serve per ricevere un carroattrezzi a Brescia?', 'Il tempo dipende dalla posizione, dal traffico e dal tipo di mezzo. Comunicare il punto esatto e spiegare bene il problema ci aiuta a organizzare il recupero con maggiore precisione.'],
  ['Posso scegliere dove portare l’auto?', 'Sì. Prima dell’intervento puoi indicare officina, carrozzeria, deposito, abitazione o un altro indirizzo concordato.'],
  ['Intervenite anche per moto e furgoni?', 'Sì. Prima di partire verifichiamo dimensioni, peso, accessi e condizioni del veicolo per predisporre il trasporto più adatto.'],
  ['Cosa devo fare se l’auto è ferma in una strada trafficata?', 'Metti in sicurezza le persone, accendi le luci di emergenza e, se possibile, raggiungi una posizione protetta. Durante la chiamata comunica carreggiata, direzione e riferimenti visibili.'],
  ['Il prezzo viene spiegato prima?', 'Raccogliamo posizione, mezzo, problema e destinazione per fornire indicazioni coerenti prima di organizzare l’uscita.'],
  ['Potete recuperare un veicolo in un parcheggio o in un cortile?', 'Sì, ma è importante conoscere accessi, rampe, larghezza e spazio di manovra. Quando serve, alcune foto aiutano a preparare meglio l’intervento.'],
]

function CallButton({ children = `Chiama ${phone}`, light = false }: { children?: React.ReactNode; light?: boolean }) {
  return <Button href={tel} className={light ? 'bg-white text-[#132844] data-hover:bg-slate-100' : 'bg-[#e85d32] text-white data-hover:bg-[#c84a22]'}>{children}</Button>
}

function Hero() {
  return <section className="relative overflow-hidden bg-[#f6f8fa]"><div className="absolute -right-32 -top-32 size-[34rem] rounded-full bg-[#f5c451]/25 blur-3xl" /><Container className="relative"><Navbar /><div className="grid gap-12 py-16 sm:py-24 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:gap-16 lg:py-28"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#e85d32]">Soccorso stradale a Brescia e provincia</p><h1 className="mt-6 max-w-2xl text-5xl font-black tracking-[-0.06em] text-[#132844] sm:text-7xl lg:text-[5.8rem] lg:leading-[0.92]">Carroattrezzi a Brescia.</h1><p className="mt-8 max-w-xl text-xl leading-8 text-slate-700 sm:text-2xl sm:leading-9">Quando un’auto si ferma, serve qualcuno che sappia trasformare una situazione confusa in un intervento chiaro. Organizziamo <strong className="text-[#132844]">soccorso stradale, traino e recupero veicoli</strong> con disponibilità 24 ore su 24.</p><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">Ci occupiamo di guasti, incidenti, batteria scarica, moto, scooter, furgoni e veicoli bloccati. Durante la chiamata raccogliamo soltanto i dati utili, così puoi capire rapidamente il prossimo passo e indicare dove portare il mezzo.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><CallButton>Chiama ora {phone}</CallButton><Button href="#servizi" variant="secondary">Vedi i servizi</Button></div><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 border-t border-slate-200 pt-6 text-sm font-semibold text-slate-600"><span><strong className="text-[#132844]">24H</strong> disponibilità</span><span><strong className="text-[#132844]">Brescia</strong> e provincia</span><span><strong className="text-[#132844]">Auto, moto</strong> e furgoni</span></div></div><div className="relative"><div className="overflow-hidden rounded-[2rem] bg-[#132844] p-3 shadow-2xl shadow-[#132844]/20"><Image src="/images/recovery-operation.jpg" alt="Operatore che carica un’auto su un carroattrezzi durante un recupero stradale" width={1800} height={1200} priority className="h-[25rem] w-full rounded-[1.4rem] object-cover sm:h-[35rem]" /><div className="absolute bottom-7 left-7 right-7 rounded-2xl bg-white/95 p-5 shadow-xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#e85d32]">Intervento su strada</p><p className="mt-2 text-lg font-extrabold text-[#132844]">Prima la sicurezza. Poi il recupero.</p></div></div></div></div></Container></section>
}

function Overview() {
  return <section className="bg-white py-20 sm:py-28"><Container className="grid gap-12 lg:grid-cols-[0.72fr_1.28fr]"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#e85d32]">Quando serve davvero</p><h2 className="mt-5 max-w-md text-4xl font-black tracking-[-0.045em] text-[#132844] sm:text-5xl">La strada si ferma. La tua assistenza no.</h2></div><div className="grid gap-6 text-lg leading-8 text-slate-700 sm:grid-cols-2"><p>Un veicolo fermo può bloccare una giornata di lavoro, un viaggio o un appuntamento importante. In quei minuti non servono spiegazioni complicate: servono una risposta diretta, una valutazione concreta e un intervento preparato sul problema reale.</p><p>Per questo chiediamo dove si trova il mezzo, che cosa è successo e quale destinazione hai in mente. Sono informazioni semplici, ma fanno la differenza quando bisogna evitare attese, manovre inutili e decisioni prese di fretta.</p><p>Il servizio di <strong>carroattrezzi a Brescia</strong> comprende recupero di auto in panne, traino dopo incidente, assistenza per moto e trasporto di veicoli non circolanti. Ogni richiesta viene valutata in base al contesto.</p><p>Se il mezzo è in una posizione pericolosa, la priorità resta sempre la sicurezza delle persone. Ti aiutiamo a comunicare il punto in modo preciso e a organizzare il trasferimento verso officina, carrozzeria, deposito o indirizzo concordato.</p></div></Container></section>
}

function Services() {
  return <section id="servizi" className="bg-[#132844] py-20 text-white sm:py-28"><Container><div className="grid gap-8 lg:grid-cols-[0.75fr_1.25fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#f5c451]">Servizi</p><h2 className="mt-4 max-w-xl text-4xl font-black tracking-[-0.045em] sm:text-5xl">Un intervento preciso per ogni tipo di fermo.</h2></div><p className="max-w-2xl text-lg leading-8 text-slate-300">Un’auto incidentata non richiede la stessa gestione di una batteria scarica. Valutiamo mezzo, posizione, accessi e destinazione per indirizzare la richiesta verso la soluzione più sensata.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-3xl bg-white/15 sm:grid-cols-2 lg:grid-cols-3">{services.map(([title, text], index) => <Link key={title} href={tel} className="group bg-[#132844] p-7 transition hover:bg-[#1d385b] sm:p-8"><p className="text-sm font-bold text-[#f5c451]">{String(index + 1).padStart(2, '0')}</p><h3 className="mt-14 text-xl font-extrabold text-white">{title}</h3><p className="mt-4 text-sm leading-6 text-slate-300">{text}</p><span className="mt-7 inline-flex text-sm font-bold text-[#f5c451]">Parla con noi <span className="ml-2 transition group-hover:translate-x-1">→</span></span></Link>)}</div></Container></section>
}

function FieldImages() {
  return <section className="bg-[#f6f8fa] py-20 sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#e85d32]">Sul posto</p><h2 className="mt-4 max-w-md text-4xl font-black tracking-[-0.045em] text-[#132844] sm:text-5xl">Attrezzatura, metodo e attenzione al veicolo.</h2></div><p className="max-w-2xl text-lg leading-8 text-slate-700">Un recupero corretto non è soltanto una questione di velocità. Conta come viene raggiunto il mezzo, come viene messo in sicurezza e come viene fissato durante il trasporto. Per questo ogni intervento parte da una valutazione concreta della situazione.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2"><article className="overflow-hidden rounded-3xl bg-white shadow-sm md:col-span-2 md:grid md:grid-cols-2"><Image src="/images/recovery-road.png" alt="Carroattrezzi con auto in recupero lungo una strada" width={1800} height={1200} className="h-72 w-full object-cover md:h-full" /><div className="p-8 sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#e85d32]">Recupero ordinato</p><h3 className="mt-4 text-3xl font-black tracking-[-0.04em] text-[#132844]">Dalla posizione alla destinazione, senza passaggi confusi.</h3><p className="mt-5 text-base leading-7 text-slate-600">Quando l’auto non può proseguire, definiamo insieme il luogo di consegna e le informazioni necessarie per procedere. Questo rende più semplice organizzare l’intervento e riduce il rischio di sorprese durante il recupero.</p><CallButton>Chiama {phone}</CallButton></div></article><article className="overflow-hidden rounded-3xl bg-white shadow-sm"><Image src="/images/home-hero.jpg" alt="Carroattrezzi pronto per un intervento di soccorso a Brescia" width={1100} height={800} className="h-64 w-full object-contain bg-slate-100" /><div className="p-7"><h3 className="text-xl font-extrabold text-[#132844]">Auto, moto e furgoni</h3><p className="mt-3 text-sm leading-6 text-slate-600">Prima di partire valutiamo dimensioni, peso, accessi e condizioni del mezzo.</p></div></article><article className="overflow-hidden rounded-3xl bg-white shadow-sm"><Image src="/images/recovery-operation.jpg" alt="Tecnico che mette in sicurezza un’auto per il trasporto" width={1100} height={800} className="h-64 w-full object-cover" /><div className="p-7"><h3 className="text-xl font-extrabold text-[#132844]">Sicurezza prima di tutto</h3><p className="mt-3 text-sm leading-6 text-slate-600">In caso di strada trafficata, incidente o posizione scomoda, raccogliamo i dettagli essenziali prima dell’uscita.</p></div></article></div></Container></section>
}

function Zones() { return <section id="zone" className="bg-white py-20 sm:py-28"><Container><div className="grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#e85d32]">Zone servite</p><h2 className="mt-4 text-4xl font-black tracking-[-0.045em] text-[#132844] sm:text-5xl">Brescia e i comuni vicini.</h2></div><p className="max-w-2xl text-lg leading-8 text-slate-700">Interveniamo in città, nelle aree industriali, lungo le tangenziali e nei principali comuni della provincia. Indicare il punto esatto ci permette di capire più velocemente accessi, traffico e destinazione del recupero.</p></div><div className="mt-12 grid grid-cols-2 gap-x-6 gap-y-4 border-t border-slate-200 pt-8 text-sm font-bold text-[#132844] sm:grid-cols-3 lg:grid-cols-4">{zones.map((zone) => <a key={zone} href={tel} className="border-b border-slate-100 pb-4 transition hover:border-[#e85d32] hover:text-[#e85d32]">Carroattrezzi a {zone}</a>)}</div></Container></section> }

function Faq() { return <section id="faq" className="bg-[#f6f8fa] py-20 sm:py-28"><Container><div className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#e85d32]">Domande frequenti</p><h2 className="mt-4 text-4xl font-black tracking-[-0.045em] text-[#132844] sm:text-5xl">Risposte utili prima della chiamata.</h2></div><div className="divide-y divide-slate-200 border-y border-slate-200">{faqs.map(([q, a]) => <details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-extrabold text-[#132844]"><span>{q}</span><span className="text-2xl font-normal text-[#e85d32] transition group-open:rotate-45">+</span></summary><p className="max-w-3xl pt-4 text-base leading-7 text-slate-600">{a}</p></details>)}</div></div></Container></section> }

function Cta() { return <section id="contatti" className="bg-[#e85d32] py-20 text-white sm:py-24"><Container className="flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-white/75">Intervento 24 ore</p><h2 className="mt-4 max-w-2xl text-4xl font-black tracking-[-0.045em] sm:text-5xl">Veicolo fermo a Brescia?</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/85">Chiama e comunicaci posizione, tipo di mezzo e problema. Organizziamo il soccorso stradale con una procedura chiara, dalla prima risposta fino alla destinazione concordata.</p></div><CallButton light>Chiama {phone}</CallButton></Container></section> }

function JsonLd() { const local = { '@context': 'https://schema.org', '@type': ['LocalBusiness', 'AutomotiveBusiness'], name: 'Carroattrezzi Brescia 24H', url: 'https://carroattrezzibrescia24.it', telephone: '+390302041924', address: { '@type': 'PostalAddress', streetAddress: address, addressLocality: 'Brescia', addressCountry: 'IT' }, areaServed: ['Brescia', ...zones], openingHours: 'Mo-Su 00:00-23:59' }; const faq = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) }; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(local) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faq) }} /></> }

export default function Home() { return <div className="min-h-screen overflow-x-hidden bg-white text-slate-900"><JsonLd /><Hero /><main><Overview /><Services /><FieldImages /><Zones /><Faq /><Cta /></main><Footer /></div> }
